on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
      - run: make test
      - run: make build
      - run: |
          diff=$(gofmt -d -e -l)
          test -z "$diff" || {
            echo "$diff"
            echo "forgot to run `make fmt`?"
            exit 1
          }
